sudo: required
services:
  - docker
 
before_install:
  - docker build -t kaharon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kaharon/react-test npm test -- --coverage

after_success:
  - docker build -t kaharon/multi-client ./client
  - docker build -t kaharon/multi-nginx ./nginx
  - docker build -t kaharon/multi-server ./server
  - docker build -t kaharon/multi-worker ./worker

  # push to docker hub
  # login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kaharon/multi-client
  - docker push kaharon/multi-server
  - docker push kaharon/multi-nginx
  - docker push kaharon/multi-worker

