sudo: required
services:
  - docker
 
before_install:
  - docker build -t kfiraharon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kfiraharon/react-test npm test

after_success:
  - docker build -t kfiraharon/multi-client ./client
  - docker build -t kfiraharon/multi-nginx ./nginx
  - docker build -t kfiraharon/multi-server ./server
  - docker build -t kfiraharon/multi-worker ./worker

  # push to docker hub
  # login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kfiraharon/multi-client
  - docker push kfiraharon/multi-server
  - docker push kfiraharon/multi-nginx
  - docker push kfiraharon/multi-worker

